- name: Add csi-driver-nfs chart repo
  kubernetes.core.helm_repository:
    name: csi-driver-nfs
    repo_url: "{{ csi_driver_nfs_dl }}"

- name: Install csi-driver-nfs chart
  kubernetes.core.helm:
    name: csi-driver-nfs
    chart_ref: csi-driver-nfs/csi-driver-nfs
    namespace: kube-system
    timeout: 10m0s
    wait: true

- name: Create StorageClass
  kubernetes.core.k8s:
    state: present
    template:
      path: 'sc-nfs.yaml'
      variable_start_string: '[['
      variable_end_string: ']]'
