- name: Add portainer chart repo
  kubernetes.core.helm_repository:
    name: portainer
    repo_url: "{{ portainer_helm }}"

- name: Create namespace
  kubernetes.core.k8s:
    name: portainer
    kind: namespace
    state: present

- name: Install portainer chart
  kubernetes.core.helm:
    name: portainer
    chart_ref: portainer/portainer
    namespace: portainer
    set_values:
      - value: service.type=LoadBalancer
      - value: tls.force=true
    wait: true

- name: Get portainer URI
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Service
    name: portainer
    namespace: portainer
  register: portainer_service

- name: Save the URI in a host fact
  ansible.builtin.set_fact:
    portainer_uri: "https://{{ portainer_service.resources[0].spec.loadBalancerIP }}:9443"

- name: Display portainer message
  ansible.builtin.debug:
    msg: "Portainer URI is https://{{ portainer_service.resources[0].spec.loadBalancerIP }}:9443"

# Test if portainer admin password already set - will return HTTP 404 if not already set:
- name: Test portainer admin password status
  ansible.builtin.uri:
    url: "https://{{ portainer_service.resources[0].spec.loadBalancerIP }}:9443/api/users/admin/check"
    validate_certs: false
    return_content: false
    status_code: [202, 404]
  register: portainer_admin_result

# Only attempt to set password if HTTP 404 returned from previous step (prevents errors on multiple runs):
- name: Set portainer admin password
  ansible.builtin.uri:
    url: https://{{ portainer_service.resources[0].spec.loadBalancerIP }}:9443/api/users/admin/init
    validate_certs: false
    method: POST
    body_format: json
    body:
      username: admin
      password: "{{ portainer_password }}"
  when: portainer_admin_result.status == 404
