# Use the community.vmware module to deploy VMs from packer template
- name: Deploy vSphere VM from template
  delegate_to: localhost                        # Must run from 'localhost' since nodes not deployed (yet)
  community.vmware.vmware_guest:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter: '{{ vcenter_datacenter }}'
    validate_certs: '{{ vcenter_validate_certs }}'
    folder: '{{ vcenter_destination_folder }}'
    template: '{{ vm_template }}'
    name: '{{ inventory_hostname }}'
    state: 'poweredon'
    cluster: '{{ vcenter_cluster }}'
    disk:
      '{{ vm_disk }}'                           # vm_disk contains 1 (or more for NFS server) disk configurations
    hardware:
      memory_mb: '{{ vm_ram_gb * 1024 }}'
      num_cpus: '{{ vm_vcpus }}'
      scsi: 'paravirtual'
    networks:
      - name: '{{ vcenter_network_name }}'
        start_connected: true
        device_type: '{{ vm_net_type }}'
        type: static
        ip: '{{ ansible_host }}'                # Static IP for this VM assigned
        netmask: '{{ vm_net_mask }}'
        gateway: '{{ vm_net_gw }}'
    customization:
      domain: '{{ dns_domain_name }}'
      dns_servers: '{{ dns_servers }}'
    wait_for_ip_address: true                   # Wait for VM to reboot and get static ip assigned before continuing

# Create /etc/hosts file entries for all hostnames & ip addresses (see conditions below)
- name: Update /etc/hosts with names
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item].ansible_host }}  {{ hostvars[item].inventory_hostname }} {{ hostvars[item].inventory_hostname }}.{{ dns_domain_name }}"
    state: present
  when:
    - inventory_hostname in groups["k8s_nodes"] # Create /etc/hosts entries on all cluster nodes
    - item != inventory_hostname                # Don't add line for ourselves to our own host file (will exist already)
    - use_hosts_file                            # Unless we're using DNS instead of /etc/hosts files
  with_items: "{{ groups.k8s_all_nodes }}"      # Add entries for all hosts including cluster_ip and NFS server
