- name: Deploy vSphere VM from template
  delegate_to: localhost
  community.vmware.vmware_guest:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter: '{{ vcenter_datacenter }}'
    validate_certs: '{{ vcenter_validate_certs }}'
    folder: '{{ vcenter_destination_folder }}'
    template: '{{ vm_template }}'
    name: '{{ inventory_hostname }}'
    state: 'poweredon'
    cluster: '{{ vcenter_cluster }}'
    disk:
      '{{ vm_disk }}'
    hardware:
      memory_mb: '{{ vm_ram_gb * 1024 }}'
      num_cpus: '{{ vm_vcpus }}'
      scsi: 'paravirtual'
    networks:
      - name: '{{ vcenter_network_name }}'
        start_connected: true
        device_type: '{{ vm_net_type }}'
        type: static
        ip: '{{ ansible_host }}'
        netmask: '{{ vm_net_mask }}'
        gateway: '{{ vm_net_gw }}'
    customization:
      domain: '{{ dns_domain_name }}'
      dns_servers: '{{ dns_servers }}'
    wait_for_ip_address: true

- name: Updte /etc/hosts with names
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item].ansible_host }}  {{ hostvars[item].inventory_hostname }} {{ hostvars[item].inventory_hostname }}.{{ dns_domain_name }}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"
