- name: Apply kube-vip cloud controller yaml
  kubernetes.core.k8s:
    state: present
    src: https://raw.githubusercontent.com/kube-vip/kube-vip-cloud-provider/main/manifest/kube-vip-cloud-controller.yaml

- name: Create kube-vip configmap
  kubernetes.core.k8s:
    namespace: kube-system
    name: kubevip
    definition:
      apiVersion: v1
      kind: ConfigMap
      data:
        cidr-global: "{{ kube_vip_ingress_cidr }}"
    apply: true
