- name: Apply kube-vip cloud controller yaml
  kubernetes.core.k8s:
    state: present
    src: "{{ kube_vip_cc_dl }}"

- name: Create kube-vip configmap
  kubernetes.core.k8s:
    namespace: kube-system
    name: kubevip
    definition:
      apiVersion: v1
      kind: ConfigMap
      data:
        cidr-global: "{{ kube_vip_ingress_cidr }}"
    apply: true
