- name: Add csi-driver-nfs chart repo
  kubernetes.core.helm_repository:
    name: csi-driver-nfs
    repo_url: "https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts"

- name: Install csi-driver-nfs chart
  kubernetes.core.helm:
    name: csi-driver-nfs
    chart_ref: latest/csi-driver-nfs
    namespace: kube-system
    wait: true

- name: Create StorageClass
  kubernetes.core.k8s:
    state: present
    template:
      path: 'sc-nfs.yaml'
      variable_start_string: '[['
      variable_end_string: ']]'
